spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql= rue
spring.jpa.properties.hibernate.show_sql=tr
spring.datasource.generate-unique-name=false
logging.level.org.springframework=debug
logging.level.org.springframework.web=debug